import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication


class Ui_Mein_Menu(object):
    def setupUi(self, Mein_Menu):
        Mein_Menu.setObjectName("Mein_Menu")
        Mein_Menu.resize(740, 700)
        Mein_Menu.setStyleSheet("background-color: rgb(56, 169, 255);")
        self.centralwidget = QtWidgets.QWidget(Mein_Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(0, 0, 141, 61))
        self.settings.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(255, 0, 127);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.settings.setObjectName("settings")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(120, 350, 500, 71))
        self.play.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"color: rgb(255, 0, 127);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.play.setObjectName("play")
        self.Name_Cirtet = QtWidgets.QLabel(self.centralwidget)
        self.Name_Cirtet.setGeometry(QtCore.QRect(220, 170, 300, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Name_Cirtet.setFont(font)
        self.Name_Cirtet.setStyleSheet("color: rgb(85, 255, 255);")
        self.Name_Cirtet.setObjectName("Name_Cirtet")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 550, 20, 20))
        self.label.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 570, 20, 20))
        self.label_2.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 590, 20, 20))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 590, 20, 20))
        self.label_4.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 600, 20, 20))
        self.label_5.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(500, 600, 20, 20))
        self.label_6.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 600, 20, 20))
        self.label_7.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 600, 20, 20))
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 490, 20, 20))
        self.label_9.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(340, 510, 20, 20))
        self.label_10.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(170, 0, 255);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 510, 20, 20))
        self.label_11.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(360, 530, 20, 20))
        self.label_12.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(170, 85, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(120, 220, 20, 20))
        self.label_13.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(120, 240, 20, 20))
        self.label_14.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(140, 220, 20, 20))
        self.label_15.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(140, 240, 20, 20))
        self.label_16.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 85, 255);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(620, 70, 20, 20))
        self.label_17.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 127);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(620, 90, 20, 20))
        self.label_18.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(620, 110, 20, 20))
        self.label_19.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 255, 0);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(600, 110, 20, 20))
        self.label_20.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(0, 680, 20, 20))
        self.label_21.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 680, 20, 20))
        self.label_22.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 0, 255);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(0, 660, 20, 20))
        self.label_23.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 255, 0);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(720, 680, 20, 20))
        self.label_24.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 85, 0);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(720, 660, 20, 20))
        self.label_25.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 0, 0);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(700, 680, 20, 20))
        self.label_26.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(720, 0, 20, 20))
        self.label_27.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(700, 0, 20, 20))
        self.label_28.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 170, 127);")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(720, 20, 20, 20))
        self.label_29.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 255, 0);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(230, 610, 20, 20))
        self.label_30.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 127);")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(250, 610, 20, 20))
        self.label_31.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 85, 0);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(250, 630, 20, 20))
        self.label_32.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(170, 0, 127);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(270, 630, 20, 20))
        self.label_33.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 255);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(650, 210, 20, 20))
        self.label_34.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(650, 230, 20, 20))
        self.label_35.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 255, 0);")
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(670, 230, 20, 20))
        self.label_36.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(670, 250, 20, 20))
        self.label_37.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 255, 0);")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(270, 40, 20, 20))
        self.label_38.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 127);")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(290, 40, 20, 20))
        self.label_39.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(310, 40, 20, 20))
        self.label_40.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(290, 60, 20, 20))
        self.label_41.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(170, 170, 255);")
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(640, 490, 20, 20))
        self.label_42.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 0, 255);")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(660, 490, 20, 20))
        self.label_43.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 0, 255);")
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(660, 470, 20, 20))
        self.label_44.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(85, 255, 0);")
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(660, 510, 20, 20))
        self.label_45.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        Mein_Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mein_Menu)
        QtCore.QMetaObject.connectSlotsByName(Mein_Menu)

    def retranslateUi(self, Mein_Menu):
        _translate = QtCore.QCoreApplication.translate
        Mein_Menu.setWindowTitle(_translate("Mein_Menu", "Меню"))
        self.settings.setText(_translate("Mein_Menu", "Настройки"))
        self.play.setText(_translate("Mein_Menu", "Играть"))
        self.Name_Cirtet.setText(_translate("Mein_Menu", "<html><head/><body><p align=\"center\">Cirtet</p></body></html>"))